name: Generate Release Notes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_notes:
    runs-on: ubuntu-latest

    env:
      ENV_MODE: dev
      OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
      AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyGithub

      - name: Generate release notes
        run: python main.py

      - name: Check generated files
        run: ls -l

      - name: Commit release notes if present
        run: |
          if [ -f RELEASE_NOTES.md ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add RELEASE_NOTES.md
            git commit -m "chore: update release notes"
            git push
          else
            echo "RELEASE_NOTES.md not found, skipping commit."